### PR TITLE
Fixed the template override issue

### LINKED ISSUE #332: Themeing a wp-maintenance mode template from within my child theme
Hi team

Previously, I have written some code to allow me to use my own maintenance mode landing theme page, but have it inside my theme directory.  In the child theme directory I had:

wp-content
- themes
- - my child theme
- - -  wp-maintenance-mode.php
- - -  wp-maintenance-mode.css

But with a recent update, these are now broken.  Although they still load, the website shows underneath them on the website landing page.

So - if we want to customise a theme, and use it from inside our child theme, what is the best way to do that now ?

Is this still the recommended method:

https://wordpress.org/support/topic/feature-request-allow-overriding-templates/#post-12025524

Thank you

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #332

### CODE REVIEW

**Comment by selul** [comment]
@arinaturcu when you get some time could you please review this.

**Comment by selul** [comment]
yes, the link expires after one month; my bad. you can test by getting the updated URL here https://github.com/Codeinwp/wp-maintenance-mode/pull/333#issuecomment-1266932296

File: views/wpmm-page-template.php [hunk 1]
```diff
@@ -3,7 +3,18 @@
...
+defined( 'ABSPATH' ) || exit;
+
+$settings              = WP_Maintenance_Mode::get_instance()->get_plugin_settings();
+$overrideable_template = wpmm_get_template_path( 'maintenance.php', true );
+
+if ( ( isset( $settings['design']['page_id'] ) && get_option( 'wpmm_new_look' ) ) && WPMM_VIEWS_PATH . 'maintenance.php' !== $overrideable_template ) {
+	if ( ! is_front_page() ) {
+		wp_redirect( home_url() );
+	}
+} else {
```
Comment (arinaturcu) [inline views/wpmm-page-template.php:15]: The first two conditions are already checked before entering this file, so there is no need to check them again.

The overriding template is loaded only when the user gets to see the maintenance state of the site, so we could define a constant in `maintenance.php` like this `define( IS_MAINTENANCE, true )` to know when that happens. 

Otherwise, the user will just get redirected to the home page (which is not desired when the user is logged in)

```suggestion
$overrideable_template = wpmm_get_template_path( 'maintenance.php', true );
if ( defined( IS_MAINTENANCE ) && WPMM_VIEWS_PATH . 'maintenance.php' !== $overrideable_template ) {
	exit();
}

$settings = WP_Maintenance_Mode::get_instance()->get_plugin_settings();
```

Comment (girishpanchal30) [reply views/wpmm-page-template.php]: @arinaturcu, I've applied your suggestions. please review and do let me know if you have any queries.

Comment (arinaturcu) [reply views/wpmm-page-template.php]: My bad here, we should add the `define( 'IS_MAINTENANCE', true )` in `includes/classes/wp-maintenance-mode.php` at line 688 after the checks to make it work:

https://github.com/Codeinwp/wp-maintenance-mode/blob/110a1dec6e52949d6f88fa97387b63e86bbdfde0/includes/classes/wp-maintenance-mode.php#L673-L687

Other than that, it's looking good, thanks! 🚀

**Comment by arinaturcu** [comment]
Thank you @girishpanchal30 🚀 

Tested and it works fine @selul, I think it's ready.
