### PR TITLE
Fixed compatibility issue with Elementor

### LINKED ISSUE #441: Conflict with Elementor
### Description

When the plugin is installed and configured, it causes issues with the Elementor editor. Users attempting to edit pages find that the editor appears to load indefinitely and only allows access in safe mode. When entering safe mode, a broken version of the page is displayed, which differs significantly from the intended design. This problem occurs only if the page is imported right after installing the plugin when that menu appears and lets you choose the template you want. 

### Step-by-step reproduction instructions

Note: It doesn’t matter if you have Elementor already installed or if you install it after LightStart as long as you follow all the steps
1. Install LightStart
2. From the menu that appears right after Installing and Activating it choose a template and click Continue
3. Click on View Page
4. Make sure you have Elementor installed
5. Click Edit with Elementor on the page just imported with LightStart

### Screenshots, screen recording, code snippet or Help Scout ticket

Thread on forum: https://wordpress.org/support/topic/elementor-crash-with-lightstart/

This is how the page appears if you enable safe mode when replicating the issue: 
Screenshot 2024-08-06 at 15 37 17

This is how the page should actually look like:
Screenshot 2024-08-06 at 15 37 27

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

In this PR I've fixed the compatibility issue with the Elementor plugin.

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes #441

### CODE REVIEW

File: includes/classes/wp-maintenance-mode.php [hunk 1]
```diff
@@ -1067,6 +1067,18 @@ public function add_maintenance_template( $templates ) {
...
+
+			// Return the default template if Elementor edit mode.
+			if ( class_exists( '\Elementor\Plugin', false ) && ( isset( $_GET['action'] ) && 'elementor' === $_GET['action'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+				return $template;
+			}
+
+			// Return the default template if Elementor preview mode.
+			if ( class_exists( '\Elementor\Plugin', false ) && isset( $_GET['elementor-preview'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+				return $template;
+			}
```
Comment (Soare-Robert-Daniel) [inline includes/classes/wp-maintenance-mode.php:1079]: Looking nice. One small preference, we can group the conditions like this along with the explanations:

```php
// Return the default template for Elementor when:
if (
    class_exists( '\Elementor\Plugin', false ) &&
    (
        // Edit Mode is on.
        ( isset( $_GET['action'] ) && 'elementor' === $_GET['action'] ) || // phpcs:ignore WordPress.Security.NonceVerification.Recommended
        // Preview Mode is on.
        isset( $_GET['elementor-preview'] ) // phpcs:ignore WordPress.Security.NonceVerification.Recommended
    )
) { 
    return $template;
}
```

Comment (girishpanchal30) [reply includes/classes/wp-maintenance-mode.php]: Done! Thank you for review

**Review by Soare-Robert-Daniel — APPROVED** [review]
