### PR TITLE
Otter form save subscriber entry

### LINKED ISSUE #323: Subscriber form not registering subscriber[in v2.5.1]
### Description:
Hey, a user reported that Subscribe form is not registering the subscriber data which can be found in WP- Maintenance Mode Settings > Modules. On this page, you can observe that the subscribe stats is still 0. A similar issue has been reported in the past https://github.com/Codeinwp/wp-maintenance-mode/issues/303

I myself have tried replicating this issue and this happens for me too. I have set up the SMTP  server and My subscribe form is working fine i.e I am able to receive the emails in my Gmail but when I went to check the subscribe stats it still shows 0. I downgraded the plugin version to 2.4.7 and on that version subscribe form stats are working fine i.e they are showing the correct No. and also we can access them as CSV files. So the issue that I am able to identify is that the new templates that are being created by the otter plugin are not linked correctly to the wp maintenance plugin that's why even after multiple subscribe form entries it still shows 0.

### How to reproduce:

1. Install the plugin and set up an SMTP server (I have added a tutorial link below) so that the form on the Maintenance mode template can work correctly.
2. After setting up the server, activate the Maintenance mode and use the coming soon template which has the subscribe form.
3. Open the page in a new tab where you are not logged in (go incognito). 
4. Enter some entries in the form.
5. Check it, You will receive the entries in your mail. 
6. Go to Settings> Modules. 
7. Observe the stats, you will see it's still 0.
8. Now roll back to version (2.4.7) which doesn't need the otter plugin for subscribe form.
9. Activate maintenance mode and enable the **show subscribe** option and do a form entry again.
10. Come back to the same settings page and observe that the subscribe stats are increased to 1. 

### Expected behavior:
The stats should increase with each form entry and form entries should be accessible through Wp maintenance settings as a CSV file like the previous version.
### Current behavior:
The subscribe stats are stuck at 0.
### Reference:
The form :
image

Plugin settings showing subscribe stats 0 (v2.5.1):
image

Plugin settings before form entry (v2.4.7):
image

Plugin settings showings stats after form entry(v2.4.7):
image

Screencast of the issue on the new version: https://www.loom.com/share/b307c82c1e4d4e2185898a50357243fb

The SMTP guide: https://docs.themeisle.com/article/1713-how-to-set-up-your-smtp-server
The ticket on HS: https://secure.helpscout.net/conversation/2016995137/337902?folderId=931544

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.5.1

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #323

### CODE REVIEW

File: includes/classes/wp-maintenance-mode.php [hunk 1]
```diff
@@ -1293,6 +1284,59 @@ public function send_contact() {
...
+			global $wpdb;
+			if ( ! empty( $email ) ) {
+				// phpcs:ignore WordPress.DB.DirectDatabaseQuery
+				$exists = $wpdb->get_row( $wpdb->prepare( "SELECT id_subscriber FROM {$wpdb->prefix}wpmm_subscribers WHERE email = %s", $email ), ARRAY_A );
+				if ( empty( $exists ) ) {
+					// phpcs:ignore WordPress.DB.DirectDatabaseQuery
+					$wpdb->insert(
+						$wpdb->prefix . 'wpmm_subscribers',
+						array(
+							'email'       => $email,
```
Comment (selul) [inline includes/classes/wp-maintenance-mode.php:1332]: @girishpanchal30 make sure to sanitize email using `sanitize_email`

**Review by selul — CHANGES_REQUESTED** [review]

File: includes/classes/wp-maintenance-mode.php (hunk 1 above)
Comment (girishpanchal30) [reply includes/classes/wp-maintenance-mode.php]: @selul Done! Thank you for the quick review.

**Review by selul — APPROVED** [review]
